name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman animation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Vishokbadri-K

      - name: Push Pacman to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: output
          user_name: "Vishokbadri-K"
          user_email: "vishokbadri1913@gmail.com"